<div id="bio" class="bg-white py-24">
  <div class="content-container">
    <img class="sm:float-left w-[300px] sm:w-[270px] md:w-[330px] mx-auto mb-8 sm:mb-4 sm:mr-6 sm:ml-0 rounded" src="<?php esc_attr_e(get_template_directory_uri() . '/src/assets/images/staff/wj-about.jpg') ?>" alt="" width="330" height="330" />
    <p class="text-justify text-lg text-[#4d4d4d] mb-4">Whitney Johnson is the CEO of human capital consultancy Disruption Advisors, an Inc. 5000 2020 fastest-growing private company in America. One of the 50 leading business thinkers in the world (#14) as named by Thinkers50, Whitney is an expert at helping individuals, teams and organizations become peak performers.</p>
    <p class="text-justify text-lg text-[#4d4d4d] mb-4">Having worked at FORTUNE 100 companies, been an award-winning equity analyst on Wall Street, invested with Harvard’s Clayton Christensen, and coached alongside the renowned Marshall Goldsmith (who selected her in 2017 from more than 16,000 candidates as a “Top 15 Coach), Whitney understandshow companies work, how investors think, and how the best coaches coach–––all of which she brings when working with and coaching CEOs and C-Suite executives.</p>
    <p class="text-justify text-lg text-[#4d4d4d] mb-4">Whitney is an award-winning author, world-class keynote speaker, and frequent lecturer for Harvard Business School’s Corporate Learning. She is a popular contributor to the Harvard Business Review, has 1.8 million followerson LinkedIn, where she was selected as a Top Voice in 2020, and her course on Fundamentals of Entrepreneurship has been viewed more than 1 million times.</p>
    <p class="text-justify text-lg text-[#4d4d4d] mb-4">An innovation and disruption theorist, Whitney is a frequent contributor to Harvard Business Review and MIT Sloan Management Review, author of the bestsellingBuild an A-Team, a Financial Times and Book of the Month andDisrupt Yourself, which Publisher’s Weekly called “Savvy . . . often counterintuitive . . . superb.” She also hosts the weekly Disrupt Yourselfpodcast whose guests have included John Mackey, Brené Brown, and Zaza Pachulia.</p>
    <p class="text-justify text-lg text-[#4d4d4d] mb-4">Whitney was the co-founder of the Disruptive Innovation Fund, involved in fund formation, capital raising, and the development of the fund’s strategy, with Harvard Business School’s Clayton Christensen. They invested and led the $8 million seed round for South Korea’s Coupang, currently valued at more than $75 billion.</p>
    <p class="text-justify text-lg text-[#4d4d4d] mb-4 clear-left">Whitney is married, has two children, and lives in Lexington, VA.</p>
    <div class="flex items-center justify-evenly flex-wrap">
      <img class="pt-8 sm:pt-4 px-6 box-content" src="<?php esc_attr_e(get_template_directory_uri() . '/src/assets/images/recognitions/thinkers50.png') ?>" alt="" width="87" height="87" />
      <img class="pt-8 sm:pt-4 px-6 box-content" src="<?php esc_attr_e(get_template_directory_uri() . '/src/assets/images/recognitions/harvardBusiness.png') ?>" alt="" width="130" height="130" />
      <img class="pt-8 sm:pt-4 px-6 box-content" src="<?php esc_attr_e(get_template_directory_uri() . '/src/assets/images/recognitions/influencer.png') ?>" alt="" width="130" height="130" />
      <img class="pt-8 sm:pt-4 px-6 box-content" src="<?php esc_attr_e(get_template_directory_uri() . '/src/assets/images/recognitions/harvardBusinessExecutive.png') ?>" alt="" width="130" height="130" />
      <img class="pt-8 sm:pt-4 px-6 box-content" src="<?php esc_attr_e(get_template_directory_uri() . '/src/assets/images/recognitions/100coaches.png') ?>" alt="" width="130" height="130" />
      <img class="pt-8 sm:pt-4 px-6 box-content" src="<?php esc_attr_e(get_template_directory_uri() . '/src/assets/images/recognitions/inc5000.png') ?>" alt="" width="79" height="58" />
    </div>
  </div>
</div>